library(readr)
heart <- read_csv("heart.csv")
summary(heart)

heart$HeartDisease <- as.factor(heart$HeartDisease)
heart$Smoking <- as.factor(heart$Smoking)
heart$AlcoholDrinking <- as.factor(heart$AlcoholDrinking)
heart$Stroke <- as.factor(heart$Stroke)
heart$DiffWalking <- as.factor(heart$DiffWalking)
heart$Sex <- as.factor(heart$Sex)
heart$AgeCategory <- as.factor(heart$AgeCategory)
heart$Race <- as.factor(heart$Race)
heart$Diabetic <- as.factor(heart$Diabetic)
heart$PhysicalActivity <- as.factor(heart$PhysicalActivity)
heart$GenHealth <- as.factor(heart$GenHealth)
heart$Asthma <- as.factor(heart$Asthma)
heart$KidneyDisease <- as.factor(heart$KidneyDisease)
heart$SkinCancer <- as.factor(heart$SkinCancer)
